name: Production Environment - CI Pipeline

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  APP_NAME: "CV Notifications API"
  RELEASE_PATH: /opt/tomcat/notifications/ROOT/
  BACKUP_NOTIFICATIONSJOBS_CLASS_PATH: /opt/tomcat/notifications/ROOT/WEB-INFBackup/classes/com/creditville/notifications/jobs/
          # /opt/tomcat/notifications/ROOT/WEB-INFBackup/classes/com/creditville/notifications/jobs
  NOTIFICATIONSJOBS_CLASS_PATH: /opt/tomcat/notifications/ROOT/WEB-INF/classes/com/creditville/notifications/jobs
  WORK_PATH: /home/ubuntu/notifications-runner/_work/CreditVille-Notifications_API/CreditVille-Notifications_API/target/notifications/


on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  deploy:
    runs-on: [self-hosted, linux, production, notification]

    steps:
      #check out repository and clone repository to the self-hosted server
      - name: Checkout the prod branch
        uses: actions/checkout@v2

      #set up Java on the server
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"


      - name: Build Application
        run: |
          mvn clean
          mvn install -DskipTests
          pwd
          cd target/notifications/
          ls -al


      # - name: Rename Existing WEB-INFBackup Directory Using Current Date
      #   run: |
      #     cd ${{ env.RELEASE_PATH }}
      #     ls -la
      #     current_date=$(date +%m-%d-%Y)
      #     echo "Current date is: $current_date"
      #     if [ -d "WEB-INFBackup" ]; then
      #       mv WEB-INFBackup WEB-INFBackup${current_date}
      #     fi
      #     ls -al

      - name: Rename Existing WEB-INFBackup Directory Using Current Date
        run: |
          cd ${{ env.RELEASE_PATH }}
          ls -la
          current_date=$(date +%m-%d-%Y)
          echo "Current date is: $current_date"
          if [ -d "WEB-INFBackup" ]; then
            if [ -d "WEB-INFBackup${current_date}" ]; then
              echo "Removing existing WEB-INFBackup${current_date} directory"
              rm -rf WEB-INFBackup${current_date}
            fi
            mv WEB-INFBackup WEB-INFBackup${current_date}
          fi
          ls -al


      - name: Backup Existing WEB-INF Directory
        run: |
          cd ${{ env.RELEASE_PATH }}
          # Check if WEB-INF exists and rename it to WEB-INFBackup
          if [ -d ${{ env.RELEASE_PATH }}WEB-INF ]; then
            mv ${{ env.RELEASE_PATH }}WEB-INF ${{ env.RELEASE_PATH }}WEB-INFBackup
          fi
          ls -al


      - name: Copy WEB-INF Directory to Notifications Directory in the Server
        run: |
          pwd
          cd ~
          cd ${{ env.WORK_PATH }}
          scp -r WEB-INF ${{ env.RELEASE_PATH }}
          sleep 10; ls -al


      - name: Replace the NotificationJobs.class With the Backup Class file stored in the Server
        run: |
          cd ${{ env.NOTIFICATIONSJOBS_CLASS_PATH}}
          ls -al
          rm NotificationJobs.class || true
          cd ${{ env.RELEASE_PATH }}
          pwd
          cp -f ${{ env.RELEASE_PATH }}NotificationJobs.class ${{ env.NOTIFICATIONSJOBS_CLASS_PATH}}
          sleep 10; 
          cd ${{ env.NOTIFICATIONSJOBS_CLASS_PATH}}
          ls -al
          sudo systemctl restart tomcat
          

        # - name: Replace the NotificationJobs.class With the Backup Class file stored in the Server
        #   run: |
        #     cd ${{ env.NOTIFICATIONSJOBS_CLASS_PATH}}
        #     ls -al
        #     rm NotificationJobs.class || true
        #     scp ${{ env.RELEASE_PATH }}NotificationJobs.class ${{ env.NOTIFICATIONSJOBS_CLASS_PATH}}
        #     sleep 10; ls -al
        #     sudo systemctl restart tomcat

